# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0075459503e0304440c6c0b9d562aba0d918dc1b2ce40aea20e31bb98de1301326449a8b2574792fcb7548d0a20b5bf1329122ffa6cf3e0a5be0c2c1eac70708

test:
  secret_key_base: ef22fd53bfc9a0323d8efbeaea1c2eab56512ceceb23bab35bb20281a41be3d848c66b51c724ca371952e7c89233b0ef923f3e6405299ccadfd5c2df2e0e31e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
